### ISSUE TITLE
Move protocols to a submodule

### ISSUE THREAD

**Issue by tsgouvea** [sanworks/Bpod#3]
In line with the issues raised by Jeff, I'd additionally suggest that Protocols be moved to a submodule, allowing it to be independently version-controlled.

**Comment by jerlich** [comment]
Settings and Data should also be in a sister repository or folder or submodules.

**Comment by tsgouvea** [comment]
Bpod currently searches for protocols, data and settings within its own file tree; but moving those to an arbitrary location could be easily dealt with by something like a 'set path'.

**Comment by sanworks** [comment]
The next push should reorganize the path, fixing these things. I'll close this thread once it's done

**Comment by sanworks** [comment]
Thanks for this feedback! It's a long time coming, and should be done by the next push. I'll close this once it's done.
