### ISSUE TITLE
Use of `run` in LaunchManager

### ISSUE THREAD

**Issue by jerlich** [sanworks/Bpod#5]
What is the advantage of using `run(ProtocolPath)` vs. `addpath(Protocolparentfolder); eval(ProtocolName)`?

I understand that `run` effectively switches to the `ProtocolPath`, which gives the side-effect of having other files in that folder on the path, but that seems a bit weak, since if other calls switch directories those other files will no longer be on the path.  

Seems safer to me to `addpath` before running the protocol and then `rmpath` at the end to avoid name conflicts.

**Comment by sanworks** [comment]
addpath and rmpath are called in RunProtocol. RunProtocol is directly called from the play/pause button (prior to the launch manager GUI, where run(protocolpath) is ).
