### ISSUE TITLE
Trinomial Polyfit very dangerous

### ISSUE THREAD

**Issue by jerlich** [sanworks/Bpod#8]
Using a trinomial fit can result in very bad interpolation.
![badcal](https://cloud.githubusercontent.com/assets/2465395/17426083/ef9e1086-5b06-11e6-8ef8-21be61f8f0e8.png)

I recommend using linear interpolation and warning about volumes that are out of the linear range.

**Comment by sanworks** [comment]
Hi Jeff. The version in this repository uses a 2nd degree (quadratic) polynomial for the fit.
